apiVersion: v1
kind: Pod
metadata:
  name: hook-preinstall
  annotations:
    "helm.sh/hook": "pre-install"
spec:
  containers:
  - name: hook1-container
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo The pre-install hook Pod is running  - hook-preinstall && sleep 15']
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
---   
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.NAME}}
  name: {{.Values.NAME}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{.Values.NAME}}
  template:
    metadata:
      labels:
        app: {{.Values.NAME}}
    spec:
      containers:
      - image: {{.Values.IMAGE}}
        imagePullPolicy: Always
        name: {{.Values.NAME}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.NAME}}
  name: {{.Values.NAME}}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{.Values.NAME}}
  type: LoadBalancer
